language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y debhelper dpkg-dev libapm-dev libupower-glib-dev libx11-dev libxss-dev fakeroot

script:
  - make BUILDDIR=default all
  - make BUILDDIR=default PREFIX=default-bin install
  - make BUILDDIR=upower USE_UPOWER=1 all
  - make BUILDDIR=upower-x11 USE_UPOWER=1 USE_X11=1 all
  - if [ -d ./debian ]; then dpkg-buildpackage -b -us -uc; fi
